export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST' as const;
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS'as const;
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED'as const;

export const ADD_CURRENT_INGREDIENT = 'ADD_CURRENT_INGREDIENT'as const;
export const DELETE_CURRENT_INGREDIENT = 'DELETE_CURRENT_INGREDIENT'as const;

export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST'as const;
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS'as const;
export const PLACE_ORDER_FAILED = 'PLACE_ORDER_FAILED'as const;
export const DELETE_ORDER_ID = 'DELETE_ORDER_ID'as const;

export const ADD_INGREDIENT = 'ADD_INGREDIENT'as const;
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT'as const;
export const REWRITE_INGREDIENTS = 'REWRITE_INGREDIENTS'as const;