export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST' as const;
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS'as const;
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED'as const;

export const ADD_CURRENT_INGREDIENT = 'ADD_CURRENT_INGREDIENT'as const;
export const DELETE_CURRENT_INGREDIENT = 'DELETE_CURRENT_INGREDIENT'as const;