export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST' as const;
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'as const;
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED'as const;

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'as const;
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'as const;
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED'as const;

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST'as const;
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'as const;
export const LOGOUT_USER_FAILED = 'LOGOUT_USER_FAILED'as const;

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'as const;
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'as const;
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED'as const;
export const RESET_PASSWORD_CLEAR = 'RESET_PASSWORD_CLEAR'as const;

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST'as const;
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'as const;
export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED'as const;
export const UPDATE_PASSWORD_CLEAR = 'UPDATE_PASSWORD_CLEAR'as const;

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'as const;
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'as const;
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'as const;