export const WS_CONNECTION_START_AUTH = 'WS_CONNECTION_START_AUTH' as const;
export const WS_CONNECTION_STOP_AUTH = 'WS_CONNECTION_STOP_AUTH' as const;
export const WS_CONNECTION_SUCCESS_AUTH = 'WS_CONNECTION_SUCCESS_AUTH' as const;
export const WS_CONNECTION_ERROR_AUTH = 'WS_CONNECTION_ERROR_AUTH' as const;
export const WS_CONNECTION_CLOSED_AUTH = 'WS_CONNECTION_CLOSED_AUTH' as const;
export const WS_GET_MESSAGE_AUTH = 'WS_GET_MESSAGE_AUTH' as const;
export const WS_SEND_MESSAGE_AUTH = 'WS_SEND_MESSAGE_AUTH' as const;

